os=require("os")
const util = require('util')
console.log("temporary directory" + os.tmpdir())
console.log("Hostname" + os.hostname())
console.log("OS" + os.platform() + "release: " + os.release())
console.log("Uptime" + os.uptime())/3600 + "Hours"
console.log("userinfo" + util.inspect(os.userInfo()))
console.log("Memory" + os.totalmem()/1000000000 + "Giga Byte")
console.log("free" + os.freemem()/1000000000 + "Giga Byte")
console.log("Hostname" + os.hostname())
console.log("CPU" + util.inspect(os.cpus()))
console.log("Network" + util.inspect(os.networkInterfaces()))
console.log("programme end")